module.exports = {
  loading: false,
  error: false,
  errorId: '',
  errorCode: '',
  errorMessage: '',
  errorMessageTitle: '',
  errorMessageFriendly: '',
  mode: 'betweenTwoDates',
  nowDate: 'November 16th 2018, 19:11:56',
  nowDailyDate: 'November 16th 2018',
  nowYear: '2018',
  nowMonth: 'November',
  nowDay: '16',
  nowHour: '19',
  nowMinute: '11',
  nowSecond: '55',
  baseDate: 'May 22nd 2017, 00:22:00',
  baseDateName: '',
  baseDateIsInThePast: false,
  baseYearDefined: true,
  baseMonthDefined: true,
  baseDayDefined: true,
  baseYear: '2017',
  baseMonth: 'May',
  baseMonthDayCount: 31,
  baseDay: '22',
  baseHour: '0',
  baseMinute: '22',
  baseSecond: '0',
  targetDate: 'February 19th 1975, 21:00:00',
  targetDateName: '',
  targetYearDefined: true,
  targetMonthDefined: true,
  targetDayDefined: true,
  targetYear: '1975',
  targetMonth: 'February',
  targetMonthDayCount: 28,
  targetDay: '19',
  targetHour: '21',
  targetMinute: '0',
  targetSecond: '0',
  addToBaseDateYears: null,
  addToBaseDateMonths: null,
  addToBaseDateWeeks: null,
  addToBaseDateDays: null,
  addToBaseDateHours: null,
  addToBaseDateMinutes: null,
  addToBaseDateSeconds: null,
  frontend: {
    mobileMenuStatus: false
  }
}
