
module.exports = {
  LOCALSTORAGE_NAME: 'stateMoments',
  LOCALSTORAGE_NAME_TIMESTAMP: 'stateMomentsTimeStamp',
  LOCALSTORAGE_SAVE_STATUS: false,
  MOMENT_TIME_FORMAT: 'MMMM Do YYYY, HH:mm:ss',
  MOMENT_TIME_DAILY_FORMAT: 'MMMM Do YYYY',
  TIME_SAVE_TO_LOCAL: 1000, // 1 SEC
  TIME_DELAY_ACTION: 500, // 0.5 SEC
}
